name: verify
on:
  push:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  verify:
    uses: jiaqi/cyclopsgroup/.github/workflows/maven-verify.yml@main
